service:
    message: Hello, World!

spring:
    output:
        ansi:
            enabled: ALWAYS

    datasource:
        url: jdbc:h2:file:./db/H2/data;AUTO_SERVER=TRUE
        driver-class-name: org.h2.Driver
        username: sa
        password:

    h2:
        console:
            enabled: true
            path: /h2-console

logging:
    level:
        org:
            springframework:
                security: DEBUG
        
        com:
            ibatis: DEBUG

